export const TABLE_ACTION = {
    UPDATE_FILTER_VALUE: 'UPDATE_FILTER_VALUE',
    UPDATE_ORDER_BY: 'UPDATE_ORDER_BY',
    UPDATE_ORDER: 'UPDATE_ORDER',
    UPDATE_LIMIT: 'UPDATE_LIMIT',
    UPDATE_TOTAL: 'UPDATE_TOTAL',
};
